pwa-builder/pwabuilder-api-v2

Security/index.ts
ServiceWorker/index.ts
WebManifest/index.ts

finally block kills execution and returns 500 if puppeteer fails to start

safe execution

---

WebManifest/index.ts
package-lock.json
package.json

fixes https://github.com/pwa-builder/PWABuilder/issues/1063

fixes https://github.com/pwa-builder/PWABuilder/issues/1063

---

README.md
ServiceWorker/index.ts
WebManifest/index.ts

This PR includes:
- An updated readme
- better error response for when a manifest is not found
- increase timeout of service worker test

Update master from dev

---

WebManifest/index.ts
WebManifest/mani-tests.ts

- adds maskable icon test
- organizes imports

feat(): add maskable icon test

---

Security/index.ts

fix(): protocol validity test now correctly handles different formats for the value

Security fix

---

ServiceWorker/index.ts

This should lessen the number of timeouts we get by:
- reducing the overall amount of work going on
- raise timeout

fix(): service worker test handles heavier workers

---

Site/helpers.ts
Site/index.ts
utils/Exception.ts
utils/getManifestFromFile.ts

UI work should be a fairly straightforward addition.

Azure Function to Support file

---

WebManifest/index.ts

Adds the ability for the manifest function to optionally take a raw manifest object. cc @JudahGabriel

refactor(): manifest function can accept raw manifest object

---

Offline/index.ts
Security/index.ts
ServiceWorker/index.ts
Site/index.ts
WebManifest/index.ts

This PR goes through and uses the standard `context.log` function in Azure functions to provide logs that we can then use with Application Insights. After this is merged into dev and I can verify its working in Azure then we can tweak anything we might want for prod.

feat(): logging

---

PlatformDownloadImage/index.ts
PlatformGenerateImage/function.json
PlatformGenerateImage/index.ts

resize image

---

Offline/index.ts
Platform/index.ts
PlatformDeleteCron/index.ts
PlatformOrchestrator/index.ts
Security/index.ts
ServiceWorker/index.ts
Site/index.ts
WebManifest/mani-tests.ts
package-lock.json
package.json
tsconfig.json
utils/getManifest.ts
utils/icons/index.ts
utils/interfaces.ts
utils/loadPage.ts
utils/manifest/index.ts
utils/storage/index.ts

This PR turns on strict mode and makes the necessary changes to the codebase to bring it "up to spec" for strict mode.

chore(): strict mode typescript

---

ServiceWorker/index.ts

`navigation.serviceWorker.ready` waits indefinitely until a service worker is returned.
Hence using either the drafted event or if the registration returns some semblance of a serviceworker being registered or detected to check whether or not to commit to the full allotted amount of time.

Service Worker: Kill execution early for service worker check

---

ServiceWorker/index.ts
utils/loadPage.ts

This removes an un-necessary page load I was still making with the new Lighthouse based Service Worker test and also refactors how I was getting the browser object we spawn to Lighthouse.

fix(): remove un-necessary page load

---

Offline/index.ts
utils/interfaces.ts

This PR has the following:
- implements a new offline function. This offline function is the "offline" piece of the service worker test.
- Adds a simple interface to more strongly type this code

feat(): new offline test

---

Offline/index.ts
Security/index.ts
utils/urlLogger.ts

- Added analytics for HTTPS score
- Added analytics for offline support

Added analytics for offline and HTTPS score

---

Dockerfile

remove this line, to ensure the docker file retrieves the latest puppeteer

dockerfile was forcing version

---

.gitignore
local.settings.json

This reverts commit 7b76575c04b3a623df5f5a38eb7ca11fbae6e6dc.

Revert "Add FUNCTIONS_WORKER_RUNTIME"

---

ServiceWorker/index.ts

Fixes https://github.com/pwa-builder/PWABuilder/issues/3731.

fix: pwa with undefined 'works-offline' property

---

Offline/index.ts
Security/index.ts
ServiceWorker/index.ts
Site/index.ts
package-lock.json
utils/fetch-headers.ts

Fixes: https://github.com/pwa-builder/PWABuilder/issues/3765
This PR fixes build errors caused by a ts types update

Quick fix of ts errors

---

.github/workflows/main.yml

I've also switched the dockerfile back to its original state before the error (old node version, but it's not showing up in the files changed.

Reverting to old node version and switching to staging env

---

Report/lighthouse/lighthouse.ts
tests/test_urls.json

This pull request modifies the code in `Report/lighthouse/lighthouse.ts` to add a check for the existence of `webAppReport` before accessing its properties and to use a new `writeAndExit()` function for consistent handling of writing data to stdout and exiting the process.
Main code modifications:
* <a href="diffhunk://#diff-561ffbbf58cacadd9d13586cc41b41612a2f3fac0d360fc40301b24029c02519L173-R198">`Report/lighthouse/lighthouse.ts`</a>: Added a check for the existence of `webAppReport` before accessing its properties and used a new `writeAndExit()` function for consistent handling of writing data to stdout and exiting the process. <a href="diffhunk://#diff-561ffbbf58cacadd9d13586cc41b41612a2f3fac0d360fc40301b24029c02519L173-R198">[1]</a> <a …

Fix error handling and exit process with

---

Report/index.ts
utils/analytics.ts

Tested and seems to be working fine locally. New field showed up in Azure along with passed data.

#4511: Add referrer field to APIV2 analytics

---

Report/index.ts
utils/analytics.ts
utils/analyzeServiceWorker.ts

fixes #4496
also removed some unused imports and fixed a typo

#4496: Add analytics for new app cap additions and fix typo
